project:
  type: website
  output-dir: docs

website:
  title: "Chris Sayers"
  site-url: www.csayers2.github.io/
  navbar:
    pinned: false
    #logo: photos/BFAN.png
    background: darkolivegreen
    foreground: white
    left:
      - text: About
        href: about.qmd
      - text: Research
        href: research/index.qmd
      - text: Publications
        href: publications.qmd
      - text: Photography
        href: photography/index.qmd
      - text: Contact
        href: contact.qmd
    right:
      - icon: linkedin
        href: www.linkedin.com/in/csayers2
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=bOWV5GUAAAAJ&hl=en
      - icon: researchgate
        text: RG
        href: https://www.researchgate.net/profile/Chris-Sayers
      - icon: github
        href: https://github.com/csayers2
      - icon: instagram
        href: https://www.instagram.com/c_sayers2/
      - icon: binoculars-fill
        href: https://ebird.org/profile/NTQ0NTM4/world
    search: true
  page-footer:
    center: "© Chris Sayers 2024 | Made with Quarto"
    background: darkolivegreen
    foreground: white

format:
  html:
    #fontsize: 18px
    #fontcolor: black
    grid:
      body-width: 1200px
    # some themes I like
    #theme: default
    #theme: minty
    theme: pulse
    #theme: sandstone
    css: styles.css
    toc: true

editor: visual
