---
title: "Research"
toc: true
---

### Disentangling the impacts of gold mining to biodiversity in the Amazon

A global surge in gold price is causing an ongoing gold rush in the most biodiverse place on Earth: the Amazon. Despite gold mining’s tremendous economic promise, we do not yet understand how the interacting environmental disturbances from this industry contribute to biodiversity loss. With the support of local collaborators, I am monitoring how bird communities respond to habitat degradation, pollution, hunting, and disease while surveying gold mines and conservation reserves in Peru.

Funded by NASA, Biodiversity Research Institute, UCLA Department of Ecology & Evolutionary Biology, American Ornithological Society, SoCal SETAC, UCLA Latin American Institute, and Sigma Xi Research Honor Society

### Optimizing heavy metal biomonitoring in the tropics

As mining industries expand to meet the global demand for precious minerals, heavy metal pollution is becoming commonplace throughout the tropics. Blood sampling provides a reliable, nonlethal measurement to track contamination in organisms, but storing samples can be impractical in remote field conditions. I am developing a simple, inexpensive method to assess heavy metal exposure in birds without needing refrigeration – thereby removing logistical barriers for scientists based in the tropics.

Funded by the Biodiversity Research Institute, UCLA Department of Ecology & Evolutionary Biology, American Ornithological Society, SoCal SETAC, UCLA Latin American Institute, and Sigma Xi Research Honor Society

### A collaborative framework for monitoring pollution in the tropics

#### TRACE - Tropical Research for Avian Conservation & Ecotoxicology

Environmental pollution of the global tropics outpaces our understanding of its consequences for biodiversity, and may contribute to regional bird declines. The TRACE Initiative is an international collaboration and data-sharing platform that produces, and provides open access to, emerging data on biotic contamination to better inform tropical bird conservation. To contribute to TRACE, click the button below!

Additional materials: [Presentation](https://drive.google.com/file/d/1v1J3iPvN_Q9gXq0KEizxxoDS9O73ZN4b/view?usp=sharing)

### Synthesizing over a decade of Neotropical bird mercury data 

Environmental mercury contamination has been severely neglected in the Neotropics, despite rapidly growing emissions from gold mining. To improve our understanding of mercury exposure to terrestrial biodiversity, we established exposure baselines for over 300 bird species across Central America, South America, and the West Indies, and quantified Hg prevalence and variation across taxonomic groups and functional traits.

**Sayers II, C.J.**, D.C. Evers, V. Ruiz-Gutierrez, et al. 2023. Mercury in Neotropical birds: a synthesis and prospectus on 13 years of exposure data. *Ecotoxicology* 32(8):1096-1123.

Additional materials: [Presentation](https://drive.google.com/file/d/1RY62k8pnyxc1OfmNtrhVmh-3QL67iV64/view?usp=sharing), [GitHub](https://github.com/csayers2/Neotropical-Bird-Hg-Review)

Funded by United Nations Minamata Convention on Mercury, USAID, and The Cornell Lab of Ornithology

### Assessing mercury risk in a clade of declining marsh birds 

Tidal marsh sparrows are species of conservation concern primarily due to global sea-level rise and habitat loss, but mercury pollution may present additional threats to their reproductive success and survival. We identified clear bioaccumulation differences between species of similar niches, as well as pollution hotspots in previously unsampled areas of their breeding ranges.

**Sayers II, C.J.**, M.R. Roeder, L.M. Forrette, D. Roche, G.L.B. Dupont, S.E. Apgar, A.R. Kocek, A.M. Cook, W.G. Shriver, C.S. Elphick, B. Olsen, and D.N. Bonter. 2021. Geographic variation of mercury in breeding tidal marsh sparrows of the northeastern United States. *Ecotoxicology* 30(9): 1929–1940.

Additional materials: [Slides](https://drive.google.com/file/d/1urKdDQ1bnCAlX6vZiKZ_rk5wWn8I7L9G/view?usp=sharing), [GitHub](https://github.com/csayers2/Sayers-Ammospiza-Hg-2021)

Funded by The Cornell Lab of Ornithology, Cornell University, NSF, National Fish & Wildlife Foundation, and US Fish & Wildlife Service
